### ISSUE TITLE
Uses url patterns which has been removed as of Django 1.10

### ISSUE THREAD

**Issue by Shic1983** [django-blog-zinnia/zinnia-wysiwyg-markitup#1]
`  File "/usr/local/lib/python3.6/site-packages/zinnia_markitup/admin.py", line 4, in <module>
    from django.conf.urls import patterns
ImportError: cannot import name 'patterns'`  

https://github.com/django/django/commit/d73d0e071c1b4c86d57994a0ab55a74cfe80cdf5

**Comment by Fantomas42** [comment]
Hello,

fixed in the latest release, v1.2.

Regards
